#!/bin/sh

if [ "$1" = "run" -a "$2" = "example" ]; then
	docker run \
		--rm \
		-it \
		-u `id -u`:`id -g` \
		-v `pwd`:`pwd` \
		-w `pwd` \
		-p 8080:8080 \
		node:9.2-alpine npm $@
else
	docker run \
		--rm \
		-it \
		-u `id -u`:`id -g` \
		-v `pwd`:`pwd` \
		-w `pwd` \
		node:9.2-alpine npm $@
fi
