import { AnyComponent, ComponentRegistory } from './types/vue'

import DefaultWrapper from './components/Wrapper/index.vue'

export const defaultOptions: InfoAddonOptions = {
  header: true,
  source: true,
  summary: '',
  components: null,
  wrapperComponent: DefaultWrapper,
  docsInPanel: true,
  useDocgen: true
}

/**
 * Addon options
 */
export interface InfoAddonOptions {
  /**
   * Toggles display of header with component name and description
   */
  header: boolean

  /**
   * Displays the source of story Component
   */
  source: boolean

  /**
   * Summary for the Story
   */
  summary: string

  /**
   * Explicitly specify components to display info
   */
  components: ComponentRegistory | false | null

  /**
   * Customize wrapper docs by overriding components
   */
  wrapperComponent: AnyComponent

  /**
   * Whether to show docs in panel instead of wrapping story
   */
  docsInPanel: boolean

  /**
   * Whether to use component infomation generated by vue-docgen-api
   */
  useDocgen: boolean
}
